### ISSUE TITLE
Look at test performance

### ISSUE THREAD

**Issue by cliffckerr** [InstituteforDiseaseModeling/synthpops#16]
From `pytest --durations=0`:

```
================ slowest test durations ================
23.26s call     tests/test_contacts.py::test_make_contacts_and_show_some_layers
13.24s call     tests/test_sizes.py::test_sizes
5.12s call     tests/test_contacts.py::test_make_contacts_generic
4.88s call     tests/test_api.py::test_api
4.87s call     tests/test_contacts.py::test_make_contacts
4.70s call     tests/test_contacts_layers.py::test_contacts_are_bidirectional
3.70s call     tests/test_api.py::test_plot_pop
3.36s call     tests/test_webapp_synthpops.py::test_webapp_make_contacts_and_show_some_layers
2.82s call     tests/test_webapp_synthpops.py::test_webapp_make_contacts
1.34s call     tests/test_webapp_synthpops.py::test_webapp_synthpops_calls
1.31s call     tests/test_synthpops.py::test_all
1.27s call     tests/test_contacts.py::test_make_contacts_from_microstructure
```
If we can just speed up those first 2 tests, we'll cut test time by half!

**Comment by mfisher-idmod** [comment]
There's not a whole lot I see I can do to make these 2 tests perform faster. Would it be worth having a developer look into improving the code around these areas? And also look into performance issues with PR #84 https://github.com/amath-idm/synthpops/pull/84?

**Comment by clorton** [comment]
@cliffckerr `run_tests` takes just over 30 seconds on my machine - is this still an active issue?

**Comment by ckerr-IDM** [comment]
@clorton no -- test used to take >2 min but various optimizations have gotten it down to 7 s on my computer :) (using `run_tests` which is parallelized).
