### ISSUE TITLE
Automate publishing to PyPi

### ISSUE THREAD

**Issue by lgeorge-idm** [InstituteforDiseaseModeling/synthpops#21]
Currently publishing to PyPi is manually done (by @cliffckerr).

New versions should only get published:
-  After a new release has been created 
- The release is merged into master
- Use GitHub actions (see: https://github.com/pypa/gh-action-pypi-publish)

**Comment by cliffckerr** [comment]
I prefer manual for now -- otherwise it's too easy (at least for my careless fingers) to accidentally push to master, and then you're stuck because pypi versions can't be rolled back.

**Comment by lgeorge-idm** [comment]
Closing for now. Will continue to use manual publishing.
