### ISSUE TITLE
Automate Docs build

### ISSUE THREAD

**Issue by lgeorge-idm** [InstituteforDiseaseModeling/synthpops#28]
Having a meeting to discuss requirements sometime during the week of May 25th

**Comment by cliffckerr** [comment]
Is this done?

**Comment by ishanarora04** [comment]
Hey can I pick this ? Are you accepting PRs ?

**Comment by lgeorge-idm** [comment]
@ishanarora04, thank you for reaching out on this issue! At this time, we are not accepting outside contributions.

**Comment by lgeorge-idm** [comment]
Moving docs to readthedocs.io.
