### ISSUE TITLE
Modify code for uploading country data files

### ISSUE THREAD

**Issue by skroiss-idm** [InstituteforDiseaseModeling/synthpops#43]
I'd love help modifying the code to so we can point it to country-specific data files. You had suggested modifying the contact_matrix_dic() function so we can input a file path instead of a sheet name.
https://github.com/InstituteforDiseaseModeling/synthpops/blob/master/synthpops/contact_networks.py#L1019

Also, it would be great to get your input on how to best implement these changes without creating a new branch or fork.

**Comment by DMistry-IDM** [comment]
@skroiss-idm  apologies for the super late reply on this - getting pretty swamped with issues and other modeling that needed to be done for Seattle area questions. I'm getting dev support now so we should be able to move more quickly on supporting the Pakistan work (it's one of the priorities). Can you share the provincial household matrix files with me so I can test out a solution for this? Let me know. Thanks!

**Comment by skroiss-idm** [comment]
That's great news Dina! I'll send you a DB invite to the folder where we're working on compiling those files. We're having trouble finding province level estimates for several things (school enrollment, school size, work place size, etc.) and are discussing options.

**Comment by DMistry-IDM** [comment]
Ahh okay - good to know. I think school enrollment might be found only at the national scale. And school sizes might be hard. We should figure out what reasonable estimates could be. Workplace sizes might be found looking for firm sizes? I know it might be hard.

**Comment by cliffckerr** [comment]
Closing for now, can reopen if needed
