### ISSUE TITLE
Issue with data_distributions get_head_age_brackets for other locations

### ISSUE THREAD

**Issue by skroiss-idm** [InstituteforDiseaseModeling/synthpops#44]
I'm making progress on collecting the data files we'll need to use synthpops in Pakistan. To start, I copied the files within .\data\demographics\contact_matrices_152_countries\usa and pasted them into .\data\demographics\contact_matrices_152_countries\test. That should allow me to change files one by one to make sure the code is working. I  ran the quick start code example from github, but changed the country_location to 'test' while keeping the state_location as Washington and location as seattle_metro.  This worked, which is a good first step. BUT if I delete the 'household living arrangements' folder in test (this folder sits outside of Washington), it fails.  What gives? Based on the code, I would not expect that folder to be required. If you have any suggestions, I'd be grateful.  Here's a link to my fork:
https://github.com/skroiss-idm/synthpops/tree/master/data/demographics/contact_matrices_152_countries

And a copy of part of the error message:   
```
File "C:\Users\skroiss\github\synthpops\synthpops\data_distributions.py", line 264, in get_head_age_brackets
    raise NotImplementedError("Data unavailable for the location specified. Please check input strings or set use_default to True to use default values from Seattle, Washington.")
NotImplementedError: Data unavailable for the location specified. Please check input strings or set use_default to True to use default values from Seattle, Washington.
```

**Comment by mfisher-idmod** [comment]
Hi @skroiss-idm! It sounds like you may already have some Pakistan data files for Synthpops. Would you be able to give @dennish737 & I access to your fork? We will be working on modifying Synthpops to be able to work with multiple regions including Pakistan and Senegal. This could help!

**Comment by skroiss-idm** [comment]
We switched over to compiling the data in the COVID-19/demographics folder in the IDM Dropbox. It looks like you folks have access to that, but let me know if you can't get in.  It's a mess and not finished, but I'm hoping to clean it up over the weekend.

**Comment by cliffckerr** [comment]
Solving a different way, so closing this issue for now
