### ISSUE TITLE
Numpy not found during setup

### ISSUE THREAD

**Issue by SBuxton-IDM** [InstituteforDiseaseModeling/synthpops#64]
**Summary**
When running python setup.py develop using a virtual environment from the venv python package, using the `python setup.py develop` command leads to a "module not found" error.

**To reproduce**

1. Create venv using python -m venv covid_venv, and activate
2. Git clone synthpops
3. Navigate into synthpops and run `python setup.py develop`

**Expected**
No error and full synthpops installation

**Actual**
```
Installed c:\covid_folder\venv_covid\lib\site-packages\networkx-2.5-py3.8.egg
Searching for numba
Reading https://pypi.org/simple/numba/
Downloading https://files.pythonhosted.org/packages/d4/b2/d6e507259f4630b319811b57c2bb3364d2737ae297a972a055cf40df36a5/numba-0.53.0rc2.tar.gz#sha256=710f8c1f6c47f682f60ba0e4489fbcd2999bd72189162beb8ec76a840e395cf6
Best match: numba 0.53.0rc2
Processing numba-0.53.0rc2.tar.gz
Writing C:\Users\Public\Documents\Wondershare\CreatorTemp\easy_install-8l0otda5\numba-0.53.0rc2\setup.cfg
Running numba-0.53.0rc2\setup.py -q bdist_egg --dist-dir C:\Users\Public\Documents\Wondershare\CreatorTemp\easy_install-8l0otda5\numba-0.53.0rc2\egg-dist-tmp-26y6z703
Traceback (most recent call last):
  File "C:\covid_folder\venv_covid\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
    yield saved
  File "C:\covid_folder\venv_covid\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
    yield
  File "C:\covid_folder\venv_covid\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "C:\covid_folder\venv_covid\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "C:\Users\Public\Documents\Wondershare\CreatorTemp\easy_install-8l0otda5\numba-0.53.0rc2\setup.py", line 422, in <module>
  File "C:\Users\Public\Documents\Wondershare\CreatorTemp\easy_install-8l0otda5\numba-0.53.0rc2\setup.py", line 148, in get_ext_modules
ModuleNotFoundError: No module named 'numpy'
```

**Notes**
This was pulled today off master branch, HEAD commit ID is 125835474a17f3deba2709243f2fdd2aa3a94af0

**Comment by cliffckerr** [comment]
Hi @SBuxton-IDM , thanks for finding this. Unfortunately `venv` hasn't really kept up with the installation requirements of the fancier numerical computing libraries, especially `numba` and `mkl`. As a result, we now recommend using `conda` instead (https://www.anaconda.com/products/individual). Try with `conda create -n covid_venv python=3.8`, instead of the `venv` command and see if that fixes it.

**Comment by dinacmistry** [comment]
echoing @cliffckerr, thanks for finding this. Also, would recommend you pull the latest version of master because I think there was an issue we recently fixed that affected synthpops on import. Thanks!

**Comment by MeWu-IDM** [comment]
This scenario seems only repro in venv 
using virtualenv works from https://virtualenv.pypa.io/en/latest/
it says 
```
Since Python 3.3, a subset of it has been integrated into the standard library under the venv module. 
The venv module does not offer all features of this library, to name just a few more prominent:

is slower (by not having the app-data seed method),
is not as extendable,
cannot create virtual environments for arbitrarily installed python versions (and automatically discover these),
is not upgrade-able via pip,
does not have as rich programmatic API (describe virtual environments without creating them).
```

**Comment by SBuxton-IDM** [comment]
Thank you all for the explanation!. This should really be an "inside-schools" issue since inside-schools has in the README:
"If desired, create a virtual environment using venv or conda." before installing synthpops. In the case of installing synthpops through venv this will lead to the above error. I will relabel this a documentation issue and close when inside-schools README is updated.

**Comment by SBuxton-IDM** [comment]
README updated with recent commit

**Comment by DMistry-IDM** [comment]
Seeing this is reopened - @SBuxton-IDM can you give more context about where you're running into this issue? Thx.

**Comment by SBuxton-IDM** [comment]
@dinacmistry Sorry about that, looks like I was checking through issues on my phone and hadn't realized that I reopened this on accident. Closing again.
