### ISSUE TITLE
Generated population isn't that similar to actual

### ISSUE THREAD

**Issue by cmerenstein** [InstituteforDiseaseModeling/synthpops#66]
Hi there,

I'm using synthpops for some modeling with Covasim, and I'm trying to generate a population with demographics similar to Philadelphia, PA. I forked the synthpops repo and added in the right json files for Philadelphia: https://github.com/cmerenstein/synthpops/tree/master/synthpops/data

I'm using the following code to generate and plot a population:

```
pars = dict(
    n                 = total_pop,
    rand_seed         = 19002,
    location = 'philadelphia_metro',
    state_location = 'Pennsylvania',
    country_location  = 'usa',
    smooth_ages       = 1,
    household_method  = 'infer_ages',
)

pop = sp.Pop(**pars)
pop_dict = sp.make_population(**pars)  # generate contact network

pop.plot_ages()  # plot the age distribution

plt.show()
```

The plot that it generates suggests a big difference between the generated and actual population: 

![image](https://user-images.githubusercontent.com/7004413/148414177-df1570ca-3573-4551-9b6f-df68f50f4e7b.png)

Is there something I can do to get it to more closely match the actual demographics of my city? When I try with the Seattle data it matches a lot closer, but that city seems to have a smoother demographic curve.

**Comment by dinacmistry** [comment]
Hi, yes that's expected behavior - you should switch household_method to 'fixed_ages'. It will become the default method after a version update with some other features.

**Comment by dinacmistry** [comment]
Closing this issue - reach out again if this didn't fix your issue. Thanks.
