### ISSUE TITLE
generate_contact_network_with_microstructure 

### ISSUE THREAD

**Issue by programgirl** [InstituteforDiseaseModeling/synthpops#71]
This does not complete with multiple errors, exiting with error code 1.

It is ignoring: sheet_name, verbose, plot, write, and return_popdict - the errors are being generated on line 31

which then creates problems with lines 133, 1270,  1281 in pop.py and line 1413 in sc_utils.py

All I am trying to do is to construct the four layers to use in Covasim. Are there any datasets in the project that show those four layers?

**Comment by cliffckerr** [comment]
@programgirl Thanks for letting us know! The issue was due to the PyPI version of SynthPops being outdated. If you reinstall it (`pip install synthpops --upgrade`, version 1.10.5) it should work now, for example with:
```py
import covasim as cv

sim = cv.Sim(pop_type='synthpops')
sim.run()
```
